language: python

notifications:
  email: false

sudo: true

python:
      - 3.6

before_install:
    - sudo apt install -y libdb5.3:amd64
    - ldd /usr/lib/python3.6/lib-dynload/_dbm.cpython-36m-x86_64-linux-gnu.so

install:
      - pip install -r requirements.txt

script:
      - nosetests -v
