language: python

notifications:
  email: false

sudo: true

python:
      - 3.6

before_install:
    - sudo apt install -y libgdbm3:amd64

install:
      - pip install -r requirements.txt

script:
      - nosetests -v
