language: python

notifications:
  email: false

sudo: true

python:
      - 3.6

before_install:
    - sudo apt install -y libdb5.3:amd64
    - sudo apt install -y python3-dev

install:
      - pip install -r requirements.txt

script:
      - nosetests -v
