language: python

notifications:
  email: false

sudo: true

python:
      - 3.6

before_install:
      - apt install -y python-meld3
      - apt install -y supervisor
      - apt install -y libgdbm-dev
      - pip install -r requirements.txt

script:
      - nosetests -v
